[build]
  publish = "public"
  command = "npm run build"


[build.environment]
  HUGO_VERSION = "0.60.1"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  include = ["CITE_ID"]
  include = ["TOKEN"]